set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++ CACHE FILEPATH "")

if(DEFINED ENV{LINUX_ARM64_SYSROOT} AND NOT "$ENV{LINUX_ARM64_SYSROOT}" STREQUAL "")
    set(CMAKE_SYSROOT "$ENV{LINUX_ARM64_SYSROOT}" CACHE PATH "")
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
