set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "")

if(DEFINED ENV{OSXCROSS_ARM64_CC} AND NOT "$ENV{OSXCROSS_ARM64_CC}" STREQUAL "")
    set(CMAKE_C_COMPILER "$ENV{OSXCROSS_ARM64_CC}" CACHE FILEPATH "")
else()
    set(CMAKE_C_COMPILER oa64-clang CACHE FILEPATH "")
endif()

if(DEFINED ENV{OSXCROSS_ARM64_CXX} AND NOT "$ENV{OSXCROSS_ARM64_CXX}" STREQUAL "")
    set(CMAKE_CXX_COMPILER "$ENV{OSXCROSS_ARM64_CXX}" CACHE FILEPATH "")
else()
    set(CMAKE_CXX_COMPILER oa64-clang++ CACHE FILEPATH "")
endif()

if(DEFINED ENV{MACOSX_SDK} AND NOT "$ENV{MACOSX_SDK}" STREQUAL "")
    set(CMAKE_OSX_SYSROOT "$ENV{MACOSX_SDK}" CACHE PATH "")
endif()

if(DEFINED ENV{MACOSX_DEPLOYMENT_TARGET} AND NOT "$ENV{MACOSX_DEPLOYMENT_TARGET}" STREQUAL "")
    set(CMAKE_OSX_DEPLOYMENT_TARGET "$ENV{MACOSX_DEPLOYMENT_TARGET}" CACHE STRING "")
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
